import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useState } from "react";
import { FlatList, StyleSheet, Text, TextInput, View, type TextStyle, type ViewStyle } from "react-native";
import { useColors } from "@/hooks/use-colors";
import { trpc } from "@/lib/trpc";
import { Card, DexusScreen, EmptyState, ErrorState, LoadingState, Pill, formatDate } from "@/components/dexus/primitives";
import { AdminGate } from "@/components/dexus/admin";

export default function AdminAuditScreen() { return <AdminGate title="Audit logs"><Audit /></AdminGate>; }
function Audit() { const colors = useColors(); const [query, setQuery] = useState(""); const logs = trpc.admin.auditLogs.useQuery({ query: query || undefined, limit: 100 }); if (logs.isLoading) return <DexusScreen title="Audit logs"><LoadingState label="Loading immutable administrative records…" /></DexusScreen>; return <DexusScreen title="Audit logs" subtitle="Sensitive actions are recorded server-side and cannot be edited here."><View style={[styles.search, { borderColor: colors.border, backgroundColor: colors.surface }]}><MaterialIcons name="search" size={20} color={colors.muted} /><TextInput value={query} onChangeText={setQuery} placeholder="Filter action, resource, or reason" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.foreground }]} /></View>{logs.error ? <ErrorState message={logs.error.message} onRetry={logs.refetch} /> : <FlatList data={logs.data ?? []} keyExtractor={(item) => item.id.toString()} contentContainerStyle={(logs.data?.length ?? 0) ? styles.list : styles.empty} ListEmptyComponent={<EmptyState icon="fact-check" title="No audit records yet" description="Administrative access and sensitive account actions appear here when they occur." />} renderItem={({ item }) => <Card><View style={styles.top}><Pill label={item.action.replaceAll("_", " ")} tone="warning" /><Text style={[styles.date, { color: colors.muted }]}>{formatDate(item.createdAt)}</Text></View><Text style={[styles.resource, { color: colors.foreground }]}>{item.resource}</Text><Text style={[styles.reason, { color: colors.muted }]}>{item.reason}</Text><Text style={[styles.meta, { color: colors.muted }]}>Admin #{item.adminUserId}{item.targetUserId ? ` · Target #${item.targetUserId}` : ""}</Text></Card>} />}</DexusScreen>; }
const styles = { search: { alignItems: "center", borderRadius: 14, borderWidth: StyleSheet.hairlineWidth, flexDirection: "row", gap: 8, minHeight: 46, paddingHorizontal: 12 } satisfies ViewStyle, input: { flex: 1, fontSize: 15, paddingVertical: 0 } satisfies TextStyle, list: { gap: 9, paddingBottom: 22 } satisfies ViewStyle, empty: { flexGrow: 1, paddingVertical: 22 } satisfies ViewStyle, top: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" } satisfies ViewStyle, date: { fontSize: 12 } satisfies TextStyle, resource: { fontSize: 15, fontWeight: "700", textTransform: "capitalize" } satisfies TextStyle, reason: { fontSize: 13, lineHeight: 18 } satisfies TextStyle, meta: { fontSize: 11 } satisfies TextStyle };
