import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useState } from "react";
import { Alert, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useColors } from "@/hooks/use-colors";
import { trpc } from "@/lib/trpc";
import { Card, DexusScreen, ErrorState, LoadingState, PrimaryButton, SectionHeading } from "@/components/dexus/primitives";

export default function InsightsScreen() { const colors = useColors(); const [question, setQuestion] = useState(""); const [answer, setAnswer] = useState<string | null>(null); const assistant = trpc.dexus.assistant.useMutation({ onSuccess: (data) => setAnswer(data.answer), onError: (error) => Alert.alert("Dexus couldn't answer that", error.message || "Please try again.") }); const briefing = trpc.dexus.briefing.useMutation({ onSuccess: (data) => setAnswer(data.briefing), onError: (error) => Alert.alert("Briefing unavailable", error.message || "Please try again.") }); const insights = trpc.dexus.insights.useMutation({ onSuccess: (data) => setAnswer(data.insight), onError: (error) => Alert.alert("Insights unavailable", error.message || "Please try again.") }); const sending = assistant.isPending || briefing.isPending || insights.isPending; const ask = () => { if (question.trim()) assistant.mutate({ question: question.trim() }); }; return <DexusScreen title="Insights" subtitle="A private assistant grounded in your saved information."><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scroll}><Card><Text style={[styles.cardTitle, { color: colors.foreground }]}>Ask Dexus</Text><TextInput value={question} onChangeText={setQuestion} placeholder="What should I focus on today?" placeholderTextColor={colors.muted} multiline style={[styles.input, { backgroundColor: `${colors.muted}10`, borderColor: colors.border, color: colors.foreground }]} /><PrimaryButton label="Ask Dexus" icon="auto-awesome" onPress={ask} loading={assistant.isPending} disabled={!question.trim() || sending} /></Card><View style={styles.shortcutRow}><View style={styles.shortcut}><PrimaryButton label="Daily briefing" tone="secondary" onPress={() => briefing.mutate()} loading={briefing.isPending} disabled={sending} icon="wb-sunny" /></View><View style={styles.shortcut}><PrimaryButton label="Weekly insight" tone="secondary" onPress={() => insights.mutate()} loading={insights.isPending} disabled={sending} icon="insights" /></View></View>{sending ? <LoadingState label="Dexus is reviewing only your relevant saved information…" /> : null}{answer ? <View style={styles.answerArea}><SectionHeading title="Dexus response" /><Card><View style={styles.answerHeader}><MaterialIcons name="auto-awesome" color={colors.primary} size={20} /><Text style={[styles.aiLabel, { color: colors.primary }]}>AI-generated from your Dexus</Text></View><Text style={[styles.answer, { color: colors.foreground }]}>{answer}</Text></Card></View> : <Card><Text style={[styles.cardTitle, { color: colors.foreground }]}>Grounded, not guessed</Text><Text style={[styles.helper, { color: colors.muted }]}>Dexus searches your relevant tasks, memories, knowledge, and plans. If it doesn’t have enough context, it will say so.</Text></Card>}</ScrollView></DexusScreen>; }
const styles = StyleSheet.create({ scroll: { gap: 14, paddingBottom: 24 }, cardTitle: { fontSize: 16, fontWeight: "700" }, input: { borderRadius: 14, borderWidth: StyleSheet.hairlineWidth, fontSize: 15, lineHeight: 21, minHeight: 102, padding: 12, textAlignVertical: "top" }, shortcutRow: { flexDirection: "row", gap: 10 }, shortcut: { flex: 1 }, answerArea: { gap: 9 }, answerHeader: { alignItems: "center", flexDirection: "row", gap: 7 }, aiLabel: { fontSize: 12, fontWeight: "700" }, answer: { fontSize: 15, lineHeight: 23 }, helper: { fontSize: 14, lineHeight: 20 }, });
