import { LegalDocument, type LegalSection } from "@/components/dexus/legal-document";

const sections: LegalSection[] = [
  { title: "1. Scope and effective date", paragraphs: ["This Privacy Policy describes how Dexus handles personal and workspace information in the current application. It is effective 24 August 2026 and is a working draft requiring legal review before public commercial launch.", "Dexus is an AI-powered personal knowledge and productivity application created by Dipanshu Ranjan."] },
  { title: "2. Account and authentication information", paragraphs: ["Dexus uses Supabase Auth for email-and-password account registration, sign-in, email verification, password reset, and session refresh. Dexus stores a provider identity mapping, account identifier, and may store your name, email address, sign-in method, account role, account status, and last sign-in time. The Dexus server verifies Supabase access tokens before resolving a request to a Dexus account.", "On web, Dexus stores the Supabase session in browser local storage and may use a Dexus session cookie for browser requests. On native devices, Dexus stores the Supabase session using the device secure-storage facility. Signing out clears local Supabase session information and asks the Dexus server to clear its session cookie."] },
  { title: "3. Workspace content", paragraphs: ["Dexus stores the information you create or approve in your workspace, including tasks, goals, notes, knowledge items, people, follow-ups, Brain Dumps, timeline events, profile preferences, and selected settings. These records are associated with your Dexus account in the application database.", "Dexus uses server-side user-scoped queries and server-enforced active-account checks for ordinary workspace operations. The current application design is intended to prevent one account from listing, changing, or retrieving another account’s workspace content through normal user features."] },
  { title: "4. Documents, voice notes, and file storage", paragraphs: ["If you upload a supported PDF, TXT, or DOCX document, Dexus receives the file, extracts readable text, stores document metadata and extracted text in the application database, and stores the uploaded file through server-managed object storage. Dexus currently supports files up to 5 MB in these flows.", "If you use voice input, Dexus stores the submitted audio through server-managed object storage and sends a signed file URL to the configured transcription service. The transcript is returned to the app for use in your Brain Dump flow."], bullets: ["Object keys and signed storage URLs are not displayed in ordinary user screens.", "The present application does not expose a self-service document-deletion flow; authorized administrators can soft-delete selected support resources through audited procedures."] },
  { title: "5. AI processing", paragraphs: ["Dexus may process the content you submit to provide Brain Dump extraction, assistant answers, briefings, insights, document summaries, and voice transcription. For example, Brain Dump text is sent to the configured AI processing service to propose structured items for your review. Dexus does not automatically save the resulting Brain Dump items until you approve the structured result.", "Dexus records privacy-limited AI operational metadata: request type, outcome, duration, and a broad failure category. The current telemetry design does not store raw prompts or private workspace content in its AI monitoring records."], bullets: ["AI-generated output can be incomplete or incorrect and should be reviewed before relying on it.", "The final public policy should identify the selected AI and storage services and be legally reviewed before commercial launch."] },
  { title: "6. Administrative access and audit logs", paragraphs: ["Dexus has a server-enforced administrator role. An active administrator can manage account state and may request controlled access to selected user-content categories only after giving a reason. The system records sensitive administrative actions in audit logs before returning requested content.", "Administrative monitoring uses privacy-limited metrics for storage, AI operations, and sanitized system errors. The ordinary Admin overview does not load private user content by default."], bullets: ["Administrators can create audited JSON exports for selected user-content categories.", "Administrators can suspend or deactivate accounts and can soft-delete selected resources through recorded administrative procedures."] },
  { title: "7. Cookies, local storage, and logging", paragraphs: ["Dexus uses Supabase session storage in browser local storage and a Dexus session cookie for browser authentication. On native devices, Dexus uses secure device storage for Supabase session material. The Dexus server verifies the active Supabase access token before authorizing product data operations.", "The current Dexus application code does not implement a separate advertising or marketing analytics tracker. It does create operational records for AI request status, sanitized errors, and administrative audits as described in this policy."] },
  { title: "8. Retention, deletion, and export", paragraphs: ["Dexus retains account and workspace data in the application database until it is deleted through an available feature or an authorized administrative action. The current build does not define a universal retention period or offer a self-service account-deletion workflow; those policies and tools should be established before public launch.", "Users can delete some workspace entities through existing app features. Administrators can perform limited, audited soft deletion and controlled JSON export. Individual self-service data export is not currently available."], bullets: ["Before launch, provide a verified privacy-contact method for access, correction, deletion, and export requests.", "Before launch, decide and publish retention periods, backup treatment, and document/object deletion procedures."] },
  { title: "9. Security and third parties", paragraphs: ["Dexus uses server-side Supabase token checks, role and account-status enforcement, user-scoped data operations, validated API inputs, audit logging for sensitive admin actions, and signed URLs for selected file-processing operations. These measures reduce risk but do not guarantee absolute security.", "Dexus relies on Supabase Auth for authentication and on configured infrastructure for database storage, object storage, and AI processing. This draft must be legally reviewed and completed with the final public provider list and contractual disclosures before commercial launch."], bullets: ["Do not upload information you are not authorised to share.", "Do not rely on Dexus for emergency, medical, legal, financial, or other high-risk decisions without appropriate professional review."] },
  { title: "10. Your rights, contact, and policy changes", paragraphs: ["Depending on applicable law, you may have rights to request access, correction, deletion, restriction, or export of personal information. A public privacy contact channel has not yet been configured in Dexus. Before launch, this policy must be updated with a working contact address or support route for such requests.", "Dexus may update this policy as the product or applicable requirements change. Material updates should be dated and made available in the app before they take effect."] },
];

export default function PrivacyScreen() { return <LegalDocument title="Privacy Policy" effectiveDate="24 August 2026" sections={sections} related="terms" />; }
