import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useEffect, useState } from "react";
import { FlatList, StyleSheet, Text, TextInput, View } from "react-native";
import { useColors } from "@/hooks/use-colors";
import { trpc } from "@/lib/trpc";
import { Card, DexusScreen, EmptyState, ErrorState, LoadingState, Pill } from "@/components/dexus/primitives";

export default function SearchScreen() { const colors = useColors(); const [query, setQuery] = useState(""); const [submitted, setSubmitted] = useState(""); useEffect(() => { const timer = setTimeout(() => setSubmitted(query.trim()), 350); return () => clearTimeout(timer); }, [query]); const results = trpc.dexus.search.useQuery({ query: submitted || "a" }, { enabled: Boolean(submitted) }); return <DexusScreen title="Search" subtitle="Ask naturally across your whole workspace."><View style={[styles.search, { backgroundColor: colors.surface, borderColor: colors.border }]}><MaterialIcons name="search" size={20} color={colors.muted} /><TextInput value={query} onChangeText={setQuery} autoFocus placeholder="What did I save about my ML project?" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.foreground }]} /></View>{!submitted ? <EmptyState icon="search" title="Find anything you’ve connected." description="Search tasks, knowledge, notes, goals, people, documents, brain dumps, and memories." /> : results.isLoading ? <LoadingState label="Searching your Dexus…" /> : results.error ? <ErrorState message={results.error.message} onRetry={results.refetch} /> : <FlatList data={results.data ?? []} keyExtractor={(item) => `${item.type}-${item.id}`} contentContainerStyle={(results.data?.length ?? 0) ? styles.list : styles.empty} ListEmptyComponent={<EmptyState icon="search-off" title="No relevant memories yet." description="Try a different phrase, or capture a new thought in Brain Dump." />} renderItem={({ item }) => <Card><View style={styles.head}><Pill label={item.type.replace(/([A-Z])/g, " $1")} tone="primary" /><Text style={[styles.date, { color: colors.muted }]}>{new Intl.DateTimeFormat("en", { month: "short", day: "numeric" }).format(new Date(item.createdAt))}</Text></View><Text style={[styles.title, { color: colors.foreground }]}>{item.title}</Text><Text numberOfLines={2} style={[styles.subtitle, { color: colors.muted }]}>{item.subtitle}</Text></Card>} />}</DexusScreen>; }
const styles = StyleSheet.create({ search: { alignItems: "center", borderRadius: 14, borderWidth: StyleSheet.hairlineWidth, flexDirection: "row", gap: 9, minHeight: 48, paddingHorizontal: 13 }, input: { flex: 1, fontSize: 15, paddingVertical: 8 }, list: { gap: 10, paddingBottom: 22 }, empty: { flexGrow: 1, paddingVertical: 22 }, head: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, date: { fontSize: 12 }, title: { fontSize: 15, fontWeight: "700" }, subtitle: { fontSize: 13, lineHeight: 18 }, });
