import { LegalDocument, type LegalSection } from "@/components/dexus/legal-document";

const sections: LegalSection[] = [
  { title: "1. Draft status and acceptance", paragraphs: ["These Terms of Service are a working draft for Dexus and require legal review before public commercial launch. By creating or using a Dexus account after a final version is published, you agree to the terms then in effect.", "Dexus is an AI-powered personal knowledge and productivity application created by Dipanshu Ranjan."] },
  { title: "2. The Dexus service", paragraphs: ["Dexus helps users capture thoughts, organise information, manage tasks and goals, store knowledge, work with documents, and use AI-assisted features such as Brain Dump extraction, summaries, insights, and assistant responses.", "Dexus is a productivity tool. It is not a substitute for professional medical, legal, financial, safety, or emergency advice. AI output can be incorrect, incomplete, or unsuitable for a particular purpose and should be reviewed before action."] },
  { title: "3. Accounts and responsibilities", paragraphs: ["You are responsible for maintaining the confidentiality of your account and session information, for activity performed through your account, and for providing accurate information where the service requires it. You must use only accounts you are authorised to use.", "Dexus can suspend or deactivate an account through server-enforced administrator controls when necessary for security, policy enforcement, or service integrity. Administrative account-state actions require a recorded reason."], bullets: ["Do not attempt to bypass authentication, account-status checks, access controls, or rate limits.", "Do not attempt to obtain administrator access or another user’s workspace content without authorisation."] },
  { title: "4. Acceptable use", paragraphs: ["You may use Dexus only for lawful purposes and in accordance with these Terms. You must not use the service to interfere with other users, compromise systems, upload unlawful content, infringe rights, distribute malware, or use automated means to abuse the service.", "You remain responsible for the content you submit, including tasks, notes, documents, people-related information, and Brain Dumps. Do not submit information you are not permitted to process or share."], bullets: ["Do not rely on AI output as the sole basis for consequential decisions.", "Do not upload files that contain malicious code or violate another party’s privacy, intellectual-property, or contractual rights."] },
  { title: "5. User content, documents, and AI output", paragraphs: ["You retain responsibility for your user-generated content. You grant Dexus the limited permission necessary to store, process, and display that content to provide the service, including AI-assisted features that you request.", "Uploaded documents may be processed for text extraction and summarisation. AI output is generated from submitted and relevant workspace context; it may be inaccurate and should not be treated as a factual guarantee, professional advice, or a replacement for your review."], bullets: ["Dexus does not automatically store Brain Dump extraction results until you approve them.", "Administrators may access selected content only through the controlled, reasoned, audited support procedures implemented in Dexus."] },
  { title: "6. Intellectual property and third-party services", paragraphs: ["The Dexus product identity, branding, and application materials are presented as Dexus, created by Dipanshu Ranjan. These Terms do not claim ownership of third-party infrastructure, libraries, AI models, authentication services, storage services, or other technologies used to operate Dexus.", "Dexus depends on configured third-party services for functions such as sign-in, data storage, file storage, and AI processing. Their availability and terms may affect the service."], bullets: ["You may not remove proprietary notices or misuse Dexus branding.", "You must respect third-party terms that apply to services you use through Dexus."] },
  { title: "7. Availability, changes, and data deletion", paragraphs: ["Dexus may change, suspend, or discontinue features when reasonably necessary for maintenance, security, legal compliance, or product development. The current build does not promise a service-level agreement or uninterrupted availability.", "Some user content can be deleted through existing workspace features. The current build does not yet provide a self-service account-deletion or self-service data-export workflow. Before public launch, Dexus should publish final retention, deletion, backup, and request-handling procedures."], bullets: ["Authorised administrators can suspend accounts, create audited selected-data exports, and soft-delete selected resources.", "You should keep independent copies of information you need to retain."] },
  { title: "8. Disclaimers, liability, and legal review", paragraphs: ["To the fullest extent permitted by applicable law, Dexus is provided on an “as is” and “as available” basis. This draft does not establish a governing law, venue, precise limitation of liability, or public contact address because those details have not yet been chosen and must be completed by qualified legal counsel before launch.", "Nothing in this draft limits rights that cannot be limited under applicable law. Before relying on these Terms publicly or commercially, obtain legal review tailored to the creator’s jurisdiction, business model, and selected service providers."] },
  { title: "9. Changes and contact", paragraphs: ["Dexus may update these Terms as the service or applicable requirements change. A final version should identify a working contact channel, governing-law decision, and a clear notice process before public launch.", "For now, no public legal contact channel is configured in the application. This document must be updated with an operational contact method before launch."] },
];

export default function TermsScreen() { return <LegalDocument title="Terms of Service" effectiveDate="24 August 2026" sections={sections} related="privacy" />; }
