import { Buffer } from "node:buffer";
import { PDFParse } from "pdf-parse";
import * as mammoth from "mammoth";
import { TRPCError } from "@trpc/server";
import { z } from "zod";
import { COOKIE_NAME } from "../shared/const.js";
import { priorities } from "../shared/dexus";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { ENV } from "./_core/env";
import { adminProcedure, protectedProcedure, publicProcedure, router } from "./_core/trpc";
import { answerFromContext, extractBrainDump, summarizeDocument, validateBrainDumpAnalysis } from "./ai";
import * as adminData from "./admin";
import * as db from "./db";
import { displayDocumentSummary, hasReadableDocumentText } from "./document-text";
import { storageDelete, storageGetSignedUrl, storagePut } from "./storage";
import { deleteSupabaseAuthUser } from "./supabase-admin";
import { transcribeAudio } from "./_core/voiceTranscription";

const priority = z.enum(priorities);
const dateString = z.string().date().nullable().optional();
const boundedText = (max: number) => z.string().trim().min(1).max(max);
const tags = z.array(z.string().trim().min(1).max(40)).max(8).default([]);
const taskInput = z.object({ title: boundedText(255), description: z.string().trim().max(2000).optional(), priority: priority.default("medium"), category: z.string().trim().max(80).optional(), dueDate: dateString, dueTime: z.string().trim().max(20).nullable().optional(), tags, goalId: z.number().int().positive().nullable().optional() });
const knowledgeInput = z.object({ title: boundedText(255), content: boundedText(6000), category: z.string().trim().max(80).optional(), tags });
const goalInput = z.object({ title: boundedText(255), description: z.string().trim().max(2000).optional(), category: z.string().trim().max(80).optional(), targetDate: dateString, progress: z.number().int().min(0).max(100).optional(), status: z.enum(["active", "paused", "completed", "abandoned"]).optional() });
const brainDumpInput = z.object({ originalText: boundedText(12000), analysis: z.unknown() });
const adminReason = boundedText(2000).refine((value) => value.length >= 10, "Provide a clear administrative reason of at least 10 characters.");
const accountStatus = z.enum(["active", "suspended", "deactivated"]);

function toDate(value?: string | null) { return value ? new Date(`${value}T12:00:00`) : null; }
function requestId(headers: Record<string, string | string[] | undefined>) { const value = headers["x-request-id"]; return Array.isArray(value) ? value[0] : value; }
async function documentText(buffer: Buffer, fileType: string) { if (fileType === "text/plain") return buffer.toString("utf8"); if (fileType === "application/pdf") { const parser = new PDFParse({ data: buffer }); try { return (await parser.getText()).text; } finally { await parser.destroy(); } } if (fileType === "application/vnd.openxmlformats-officedocument.wordprocessingml.document") return (await mammoth.extractRawText({ buffer })).value; throw new Error("Dexus supports PDF, TXT, and DOCX documents."); }

const activeUserProcedure = protectedProcedure.use(async ({ ctx, next }) => {
  const currentUser = await db.getUserById(ctx.user.id);
  if (!currentUser || currentUser.accountStatus !== "active") throw new TRPCError({ code: "FORBIDDEN", message: "This account is not currently active." });
  return next({ ctx: { ...ctx, user: currentUser } });
});

const administratorProcedure = adminProcedure.use(async ({ ctx, next }) => {
  const currentUser = await db.getUserById(ctx.user.id);
  if (!currentUser || currentUser.role !== "admin" || currentUser.accountStatus !== "active") throw new TRPCError({ code: "FORBIDDEN", message: "You are not authorized to access Dexus Admin." });
  return next({ ctx: { ...ctx, user: currentUser } });
});

async function trackedAi<T>(input: { userId: number; requestType: string; requestId?: string; operation: () => Promise<T> }) {
  const started = Date.now();
  try {
    const result = await input.operation();
    await adminData.recordAiRequest({ userId: input.userId, requestType: input.requestType, status: "success", durationMs: Date.now() - started });
    return result;
  } catch (error) {
    await Promise.allSettled([adminData.recordAiRequest({ userId: input.userId, requestType: input.requestType, status: "failure", durationMs: Date.now() - started, errorCategory: "request_failed" }), adminData.recordSafeError({ userId: input.userId, feature: "ai", safeMessage: "Dexus AI request failed.", requestId: input.requestId })]);
    throw error;
  }
}

export const appRouter = router({
  system: systemRouter,
  auth: router({ me: publicProcedure.query((opts) => opts.ctx.user), logout: publicProcedure.mutation(({ ctx }) => { const cookieOptions = getSessionCookieOptions(ctx.req); ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 }); return { success: true } as const; }) }),
  account: router({ delete: activeUserProcedure.input(z.object({ confirmation: z.literal("DELETE MY ACCOUNT") })).mutation(async ({ ctx }) => { const plan = await db.getOwnAccountDeletionPlan(ctx.user.id); if (ENV.ownerSupabaseUserId && plan.providerUserId === ENV.ownerSupabaseUserId) throw new TRPCError({ code: "FORBIDDEN", message: "The configured Dexus owner account cannot be deleted through self-service controls." }); for (const storageKey of plan.storageKeys) await storageDelete(storageKey); await db.deleteOwnAccountData(ctx.user.id); await deleteSupabaseAuthUser(plan.providerUserId); const cookieOptions = getSessionCookieOptions(ctx.req); ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 }); return { success: true }; }) }),
  dexus: router({
    dashboard: activeUserProcedure.query(({ ctx }) => db.dashboard(ctx.user.id)), profile: activeUserProcedure.query(({ ctx }) => db.ensureProfile(ctx.user.id, ctx.user.name)), updateProfile: activeUserProcedure.input(z.object({ displayName: z.string().trim().max(120).optional(), timezone: z.string().trim().max(80).optional(), defaultPriority: priority.optional(), appearance: z.enum(["system", "light", "dark"]).optional(), aiSuggestionsEnabled: z.boolean().optional(), notificationsEnabled: z.boolean().optional() })).mutation(({ ctx, input }) => db.updateProfile(ctx.user.id, input)),
    processBrainDump: activeUserProcedure.input(z.object({ text: boundedText(12000), timezone: z.string().trim().max(80).default("UTC") })).mutation(({ ctx, input }) => trackedAi({ userId: ctx.user.id, requestType: "brain_dump_extraction", requestId: requestId(ctx.req.headers), operation: () => extractBrainDump(input) })), saveBrainDump: activeUserProcedure.input(brainDumpInput).mutation(async ({ ctx, input }) => { const parsed = validateBrainDumpAnalysis(input.analysis); if (!parsed.success) throw new Error("Dexus could not validate the edited AI results."); await db.saveApprovedBrainDump(ctx.user.id, input.originalText, parsed.data); return { success: true }; }), search: activeUserProcedure.input(z.object({ query: boundedText(240) })).query(({ ctx, input }) => db.searchUserData(ctx.user.id, input.query)),
    assistant: activeUserProcedure.input(z.object({ question: boundedText(1200) })).mutation(async ({ ctx, input }) => { const results = await db.searchUserData(ctx.user.id, input.question); const context = results.map((item) => `[${item.type}] ${item.title}: ${item.subtitle}`).join("\n"); return { answer: await trackedAi({ userId: ctx.user.id, requestType: "assistant", requestId: requestId(ctx.req.headers), operation: () => answerFromContext(input.question, context, "assistant") }), contextCount: results.length }; }),
    briefing: activeUserProcedure.mutation(async ({ ctx }) => { const data = await db.dashboard(ctx.user.id); const context = `Open tasks: ${data.focusTasks.map((task) => `${task.title}${task.dueDate ? ` due ${task.dueDate.toISOString().slice(0, 10)}` : ""}`).join("; ")}\nOpen follow-ups: ${data.followups.map((item) => `${item.person.name}: ${item.followup.action}`).join("; ")}\nActive goals: ${data.goals.map((goal) => goal.title).join("; ")}`; return { briefing: await trackedAi({ userId: ctx.user.id, requestType: "briefing", requestId: requestId(ctx.req.headers), operation: () => answerFromContext("Create a concise daily briefing with Priority, Tasks, Follow-up, Learning, and an AI Suggestion when supported by context.", context, "briefing") }) }; }),
    insights: activeUserProcedure.mutation(async ({ ctx }) => { const data = await db.dashboard(ctx.user.id); const context = `Completed tasks: ${data.stats.completedTasks}; pending tasks: ${data.stats.pendingTasks}; active goals: ${data.stats.activeGoals}; knowledge saved: ${data.stats.knowledgeItems}; open follow-ups: ${data.stats.openFollowups}.`; return { insight: await trackedAi({ userId: ctx.user.id, requestType: "insights", requestId: requestId(ctx.req.headers), operation: () => answerFromContext("Write a concise weekly reflection with what went well, needs attention, and a clearly labeled AI suggestion. Do not make medical or psychological claims.", context, "insights") }), stats: data.stats }; }),
  }),
  tasks: router({ list: activeUserProcedure.input(z.object({ status: z.enum(["open", "completed", "archived"]).optional(), query: z.string().trim().max(120).optional() }).optional()).query(({ ctx, input }) => db.listTasks(ctx.user.id, input)), create: activeUserProcedure.input(taskInput).mutation(({ ctx, input }) => db.createTask(ctx.user.id, { ...input, dueDate: toDate(input.dueDate) })), update: activeUserProcedure.input(taskInput.partial().extend({ id: z.number().int().positive(), status: z.enum(["open", "completed", "archived"]).optional() })).mutation(({ ctx, input }) => { const { id, dueDate, ...data } = input; return db.updateTask(ctx.user.id, id, { ...data, ...(dueDate !== undefined ? { dueDate: toDate(dueDate) } : {}) }); }), delete: activeUserProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ ctx, input }) => db.deleteTask(ctx.user.id, input.id)) }),
  goals: router({ list: activeUserProcedure.query(({ ctx }) => db.listGoals(ctx.user.id)), create: activeUserProcedure.input(goalInput).mutation(({ ctx, input }) => db.createGoal(ctx.user.id, { ...input, targetDate: toDate(input.targetDate) })), update: activeUserProcedure.input(goalInput.partial().extend({ id: z.number().int().positive() })).mutation(({ ctx, input }) => { const { id, targetDate, ...data } = input; return db.updateGoal(ctx.user.id, id, { ...data, ...(targetDate !== undefined ? { targetDate: toDate(targetDate) } : {}) }); }), delete: activeUserProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ ctx, input }) => db.deleteGoal(ctx.user.id, input.id)) }),
  knowledge: router({ list: activeUserProcedure.input(z.object({ query: z.string().trim().max(120).optional() }).optional()).query(({ ctx, input }) => db.listKnowledge(ctx.user.id, input?.query)), create: activeUserProcedure.input(knowledgeInput).mutation(({ ctx, input }) => db.createKnowledge(ctx.user.id, input)), update: activeUserProcedure.input(knowledgeInput.partial().extend({ id: z.number().int().positive() })).mutation(({ ctx, input }) => { const { id, ...data } = input; return db.updateKnowledge(ctx.user.id, id, data); }), delete: activeUserProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ ctx, input }) => db.deleteKnowledge(ctx.user.id, input.id)) }),
  notes: router({ list: activeUserProcedure.query(({ ctx }) => db.listNotes(ctx.user.id)), create: activeUserProcedure.input(knowledgeInput).mutation(({ ctx, input }) => db.createNote(ctx.user.id, input)), update: activeUserProcedure.input(knowledgeInput.partial().extend({ id: z.number().int().positive() })).mutation(({ ctx, input }) => { const { id, ...data } = input; return db.updateNote(ctx.user.id, id, data); }), delete: activeUserProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ ctx, input }) => db.deleteNote(ctx.user.id, input.id)) }),
  people: router({ list: activeUserProcedure.query(({ ctx }) => db.listPeople(ctx.user.id)), create: activeUserProcedure.input(z.object({ name: boundedText(160), context: z.string().trim().max(1000).optional(), notes: z.string().trim().max(1500).optional() })).mutation(({ ctx, input }) => db.createPerson(ctx.user.id, input)), update: activeUserProcedure.input(z.object({ id: z.number().int().positive(), name: boundedText(160).optional(), context: z.string().trim().max(1000).nullable().optional(), notes: z.string().trim().max(1500).nullable().optional() })).mutation(({ ctx, input }) => { const { id, ...data } = input; return db.updatePerson(ctx.user.id, id, data); }), delete: activeUserProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ ctx, input }) => db.deletePerson(ctx.user.id, input.id)) }),
  followups: router({ list: activeUserProcedure.query(({ ctx }) => db.listFollowups(ctx.user.id)), create: activeUserProcedure.input(z.object({ personId: z.number().int().positive(), action: boundedText(255), dueDate: dateString })).mutation(({ ctx, input }) => db.createFollowup(ctx.user.id, { ...input, dueDate: toDate(input.dueDate) })), update: activeUserProcedure.input(z.object({ id: z.number().int().positive(), action: boundedText(255).optional(), dueDate: dateString, status: z.enum(["open", "completed", "snoozed"]).optional() })).mutation(({ ctx, input }) => { const { id, dueDate, ...data } = input; return db.updateFollowup(ctx.user.id, id, { ...data, ...(dueDate !== undefined ? { dueDate: toDate(dueDate) } : {}) }); }), delete: activeUserProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ ctx, input }) => db.deleteFollowup(ctx.user.id, input.id)) }),
  timeline: router({ list: activeUserProcedure.input(z.object({ limit: z.number().int().min(1).max(200).optional() }).optional()).query(({ ctx, input }) => db.listTimeline(ctx.user.id, input?.limit)) }), brainDumps: router({ list: activeUserProcedure.query(({ ctx }) => db.listBrainDumps(ctx.user.id)) }),
  documents: router({ list: activeUserProcedure.query(async ({ ctx }) => (await db.listDocuments(ctx.user.id)).map((document) => ({ ...document, summary: displayDocumentSummary(document.summary) }))), upload: activeUserProcedure.input(z.object({ filename: boundedText(255), fileType: z.enum(["application/pdf", "text/plain", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"]), base64: z.string().min(1).max(7_000_000) })).mutation(async ({ ctx, input }) => { const buffer = Buffer.from(input.base64, "base64"); if (!buffer.length || buffer.length > 5 * 1024 * 1024) throw new Error("Documents must be between 1 byte and 5 MB."); const extractedText = await documentText(buffer, input.fileType); if (!hasReadableDocumentText(extractedText)) throw new Error("Dexus could not read enough selectable text to summarize this document. For a scanned PDF, upload an OCR or text-selectable copy."); const stored = await storagePut(`${ctx.user.id}/documents/${input.filename}`, buffer, input.fileType); const summary = await trackedAi({ userId: ctx.user.id, requestType: "document_summary", requestId: requestId(ctx.req.headers), operation: () => summarizeDocument(extractedText) }); const id = await db.createDocument(ctx.user.id, { filename: input.filename, fileType: input.fileType, storageKey: stored.key, storageUrl: stored.url, extractedText: extractedText.slice(0, 100000), summary, fileSize: buffer.length }); return { id, summary }; }), regenerateSummary: activeUserProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const document = await db.getDocument(ctx.user.id, input.id); const extractedText = document?.extractedText ?? ""; if (!hasReadableDocumentText(extractedText)) throw new Error("Dexus could not read enough selectable text to summarize this document. For a scanned PDF, upload an OCR or text-selectable copy."); const summary = await trackedAi({ userId: ctx.user.id, requestType: "document_summary", requestId: requestId(ctx.req.headers), operation: () => summarizeDocument(extractedText) }); await db.updateDocumentSummary(ctx.user.id, input.id, summary); return { id: input.id, summary }; }), delete: activeUserProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const document = await db.getDocument(ctx.user.id, input.id); if (!document) throw new TRPCError({ code: "NOT_FOUND", message: "Document not found." }); await storageDelete(document.storageKey); await db.deleteDocument(ctx.user.id, document.id, document.filename); return { id: document.id }; }) }),
  adminDocuments: router({ list: administratorProcedure.input(z.object({ limit: z.number().int().min(1).max(100).default(50) }).optional()).query(({ input }) => adminData.listDocumentMetadata(input?.limit ?? 50)), delete: administratorProcedure.input(z.object({ userId: z.number().int().positive(), documentId: z.number().int().positive(), reason: adminReason })).mutation(({ ctx, input }) => adminData.deletePrivateDocument({ adminUserId: ctx.user.id, targetUserId: input.userId, documentId: input.documentId, reason: input.reason, requestId: requestId(ctx.req.headers) })) }),
  voice: router({ transcribe: activeUserProcedure.input(z.object({ filename: boundedText(255), mimeType: z.enum(["audio/mpeg", "audio/wav", "audio/mp4", "audio/m4a", "audio/webm", "audio/ogg"]), base64: z.string().min(1).max(7_000_000) })).mutation(async ({ ctx, input }) => { const buffer = Buffer.from(input.base64, "base64"); if (!buffer.length || buffer.length > 5 * 1024 * 1024) throw new Error("Voice notes must be between 1 byte and 5 MB."); const stored = await storagePut(`${ctx.user.id}/voice/${input.filename}`, buffer, input.mimeType); const transcript = await trackedAi({ userId: ctx.user.id, requestType: "voice_transcription", requestId: requestId(ctx.req.headers), operation: async () => transcribeAudio({ audioUrl: await storageGetSignedUrl(stored.key), language: "en", prompt: "Transcribe a personal productivity and knowledge note accurately." }) }); const text = "text" in transcript ? transcript.text?.trim() : ""; if (!text) throw new Error("Dexus could not transcribe that recording."); return { text }; }) }),
  admin: router({
    overview: administratorProcedure.query(() => adminData.overview()), users: administratorProcedure.input(z.object({ query: z.string().trim().max(160).optional(), status: accountStatus.optional(), limit: z.number().int().min(1).max(100).default(50) }).optional()).query(({ input }) => adminData.listUsers({ query: input?.query, status: input?.status, limit: input?.limit ?? 50 })), userDetail: administratorProcedure.input(z.object({ userId: z.number().int().positive() })).query(({ input }) => adminData.userDetail(input.userId)),
    setAccountStatus: administratorProcedure.input(z.object({ userId: z.number().int().positive(), status: accountStatus, reason: adminReason })).mutation(({ ctx, input }) => adminData.setAccountStatus({ adminUserId: ctx.user.id, targetUserId: input.userId, status: input.status, reason: input.reason, requestId: requestId(ctx.req.headers) })), accessContent: administratorProcedure.input(z.object({ userId: z.number().int().positive(), resources: z.array(z.enum(adminData.contentResources)).min(1).max(9), reason: adminReason })).mutation(({ ctx, input }) => adminData.accessUserContent({ adminUserId: ctx.user.id, targetUserId: input.userId, resources: input.resources, reason: input.reason, requestId: requestId(ctx.req.headers) })), exportUser: administratorProcedure.input(z.object({ userId: z.number().int().positive(), resources: z.array(z.enum(adminData.contentResources)).min(1).max(9), reason: adminReason })).mutation(({ ctx, input }) => adminData.exportUserData({ adminUserId: ctx.user.id, targetUserId: input.userId, resources: input.resources, reason: input.reason, requestId: requestId(ctx.req.headers) })), softDelete: administratorProcedure.input(z.object({ userId: z.number().int().positive(), resource: z.enum(["task", "brainDump", "document"]), resourceId: z.number().int().positive(), reason: adminReason })).mutation(({ ctx, input }) => adminData.softDeleteUserContent({ adminUserId: ctx.user.id, targetUserId: input.userId, resource: input.resource, resourceId: input.resourceId, reason: input.reason, requestId: requestId(ctx.req.headers) })),
    auditLogs: administratorProcedure.input(z.object({ query: z.string().trim().max(160).optional(), limit: z.number().int().min(1).max(100).default(50) }).optional()).query(({ input }) => adminData.listAuditLogs({ query: input?.query, limit: input?.limit ?? 50 })), storage: administratorProcedure.query(() => adminData.storageMetrics()), ai: administratorProcedure.query(() => adminData.aiMetrics()), errors: administratorProcedure.input(z.object({ limit: z.number().int().min(1).max(100).default(50) }).optional()).query(({ input }) => adminData.listSystemErrors(input?.limit ?? 50)), resolveError: administratorProcedure.input(z.object({ errorId: z.number().int().positive(), reason: adminReason })).mutation(({ ctx, input }) => adminData.resolveSystemError({ adminUserId: ctx.user.id, errorId: input.errorId, reason: input.reason, requestId: requestId(ctx.req.headers) })),
  }),
});

export type AppRouter = typeof appRouter;
