import { useEffect, useState } from "react";
import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useColors } from "@/hooks/use-colors";
import { PrimaryButton } from "./primitives";

export type EntityValues = { title: string; description: string; category: string; date: string; priority: "low" | "medium" | "high" };
const blank: EntityValues = { title: "", description: "", category: "", date: "", priority: "medium" };

export function EntityModal({ visible, heading, initial, onClose, onSave, onDelete, saveLabel = "Save" }: { visible: boolean; heading: string; initial?: Partial<EntityValues>; onClose: () => void; onSave: (values: EntityValues) => Promise<void>; onDelete?: () => Promise<void>; saveLabel?: string }) {
  const colors = useColors();
  const [values, setValues] = useState<EntityValues>(blank);
  const [saving, setSaving] = useState(false);
  const [deleting, setDeleting] = useState(false);
  useEffect(() => { if (visible) setValues({ ...blank, ...initial }); }, [visible, initial]);
  const change = (key: keyof EntityValues, value: string) => setValues((current) => ({ ...current, [key]: value }));
  const save = async () => { if (!values.title.trim()) return; setSaving(true); try { await onSave({ ...values, title: values.title.trim() }); onClose(); } finally { setSaving(false); } };
  const remove = async () => { if (!onDelete) return; setDeleting(true); try { await onDelete(); onClose(); } finally { setDeleting(false); } };
  return <Modal animationType="slide" transparent visible={visible} onRequestClose={onClose}><View style={styles.backdrop}><View style={[styles.sheet, { backgroundColor: colors.background }]}><View style={styles.grabber} /><View style={styles.header}><Text style={[styles.heading, { color: colors.foreground }]}>{heading}</Text><Pressable accessibilityLabel="Close" onPress={onClose} style={({ pressed }) => [styles.close, { backgroundColor: colors.surface }, pressed && styles.pressed]}><MaterialIcons name="close" size={20} color={colors.foreground} /></Pressable></View><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.form}><Field label="Title" value={values.title} onChangeText={(value) => change("title", value)} colors={colors} autoFocus /><Field label="Details" value={values.description} onChangeText={(value) => change("description", value)} colors={colors} multiline /><Field label="Category" value={values.category} onChangeText={(value) => change("category", value)} colors={colors} /><Field label="Due or target date" hint="YYYY-MM-DD" value={values.date} onChangeText={(value) => change("date", value)} colors={colors} /><Text style={[styles.label, { color: colors.foreground }]}>Priority</Text><View style={styles.priorityRow}>{(["low", "medium", "high"] as const).map((priority) => <Pressable key={priority} onPress={() => change("priority", priority)} style={({ pressed }) => [styles.priority, { borderColor: values.priority === priority ? colors.primary : colors.border, backgroundColor: values.priority === priority ? `${colors.primary}16` : colors.surface }, pressed && styles.pressed]}><Text style={[styles.priorityLabel, { color: values.priority === priority ? colors.primary : colors.muted }]}>{priority[0].toUpperCase() + priority.slice(1)}</Text></Pressable>)}</View><PrimaryButton label={saveLabel} onPress={save} loading={saving} disabled={!values.title.trim()} icon="check" />{onDelete ? <PrimaryButton label="Delete" onPress={remove} loading={deleting} tone="danger" icon="delete" /> : null}</ScrollView></View></View></Modal>;
}

function Field({ label, hint, colors, ...props }: { label: string; hint?: string; colors: ReturnType<typeof useColors>; value: string; onChangeText: (value: string) => void; multiline?: boolean; autoFocus?: boolean }) { return <View style={styles.field}><View style={styles.fieldHeading}><Text style={[styles.label, { color: colors.foreground }]}>{label}</Text>{hint ? <Text style={[styles.hint, { color: colors.muted }]}>{hint}</Text> : null}</View><TextInput value={props.value} onChangeText={props.onChangeText} multiline={props.multiline} autoFocus={props.autoFocus} placeholderTextColor={colors.muted} style={[styles.input, { backgroundColor: colors.surface, borderColor: colors.border, color: colors.foreground }, props.multiline && styles.multiline]} /></View>; }

const styles = StyleSheet.create({ backdrop: { backgroundColor: "rgba(10, 9, 20, 0.42)", flex: 1, justifyContent: "flex-end" }, sheet: { borderTopLeftRadius: 28, borderTopRightRadius: 28, maxHeight: "90%", paddingHorizontal: 20, paddingTop: 10 }, grabber: { alignSelf: "center", backgroundColor: "#9A98A8", borderRadius: 3, height: 5, width: 42 }, header: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", marginBottom: 16, marginTop: 12 }, heading: { fontSize: 21, fontWeight: "700" }, close: { alignItems: "center", borderRadius: 16, height: 36, justifyContent: "center", width: 36 }, form: { gap: 14, paddingBottom: 34 }, field: { gap: 7 }, fieldHeading: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, label: { fontSize: 13, fontWeight: "700" }, hint: { fontSize: 12 }, input: { borderRadius: 14, borderWidth: StyleSheet.hairlineWidth, fontSize: 16, minHeight: 47, paddingHorizontal: 13, paddingVertical: 12 }, multiline: { minHeight: 96, textAlignVertical: "top" }, priorityRow: { flexDirection: "row", gap: 8 }, priority: { alignItems: "center", borderRadius: 12, borderWidth: 1, flex: 1, minHeight: 40, justifyContent: "center" }, priorityLabel: { fontSize: 13, fontWeight: "700" }, pressed: { opacity: 0.72 }, });
